---

- hosts: es
  roles:
    - es

#- hosts: kibana
#  roles:
#    - kibana

# - hosts: zookeepers:elastic_with_kibanas:storm-supervisors:storm-nimbuses:kafkas
#   tasks:  
#   - include_role:
#       name: logstash

# - hosts: kafkas
#   tasks:
#   - include_role:
#       name: kafka

