---

all:
  hosts:
    es:
      ansible_host: 192.168.10.11
    kibana:
      ansible_host: 192.168.10.12
    logstash:
      ansible_host: 192.168.10.13
    filebeat:
      ansible_host: 192.168.10.14
    metricbeat:
      ansible_host: 192.168.10.14
  vars:
    ansible_port: 22
    ansible_connection: ssh
    ansible_user: vagrant
    ansible_private_key_file: "~/.vagrant.d/insecure_private_key"
    #ansible_password=
    username: vagrant
    usergroup: vagrant
    base_dir: "/opt"
    apps_dir: "{{base_dir}}/apps"
    data_dir: "{{base_dir}}/data"
    logs_dir: "{{base_dir}}/logs"
    es_api_port: 9200
    es_api_host: 192.168.10.11
    es_api_uri: "https://{{ es_api_host }}:{{ es_api_port }}"

