---

#--------- bootstrap user ----------------

- name: create the keystore if it doesn't exist yet
  command: >
    {{ es_install_dir }}/bin/elasticsearch-keystore create
  args:
    creates: "{{ es_conf_dir }}/elasticsearch.keystore"
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"

- name: getting list of keys already in keystore
  command: >
    {{es_install_dir}}/bin/elasticsearch-keystore list
  register: list_keystore
  changed_when: False
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"
  check_mode: no

- name: bootstrap password for elastic user
  shell: echo "{{es_superuser_password}}" | {{es_install_dir}}/bin/elasticsearch-keystore add -x 'bootstrap.password'
  when:
    - list_keystore is defined and 'bootstrap.password' not in list_keystore.stdout_lines
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"
#      no_log: true

- name: setting xpack.security.http.ssl.secure_key_passphrase in keystore
  shell: echo "{{tls_password}}" | {{es_install_dir}}/bin/elasticsearch-keystore add -x 'xpack.security.http.ssl.secure_key_passphrase'
  when:
    - list_keystore is defined and 'xpack.security.http.ssl.secure_key_passphrase' not in list_keystore.stdout_lines
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"

- name: setting xpack.security.transport.ssl.secure_key_passphrase in keystore
  shell: echo "{{tls_password}}" | {{es_install_dir}}/bin/elasticsearch-keystore add -x 'xpack.security.transport.ssl.secure_key_passphrase'
  when:
    - list_keystore is defined and 'xpack.security.transport.ssl.secure_key_passphrase' not in list_keystore.stdout_lines
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"


- name: Set elasticsearch.keystore Permissions
  become: yes
  file:
    state: file
    path: "{{ es_conf_dir }}/elasticsearch.keystore"
    mode: "0660"
