- name: copy elasticsearch
  copy:
    src: "files/{{es_repo_file}}"
    dest: "{{apps_dir}}/{{es_repo_file}}"
  register: copy_es

- name: create elasticsearch directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
  with_items:
    - "{{ es_install_dir }}"
    - "{{ es_data_dir }}"
    - "{{ es_logs_dir }}"

- name: extract elasticsearch
  unarchive:
    src: "{{ apps_dir }}/{{ es_repo_file }}"
    dest: "{{ es_install_dir }}/"
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: copy_es.changed

- name: copy elasticsearch config
  template:
    src: "elasticsearch.yml.j2"
    dest: "{{ es_install_dir }}/config/elasticsearch.yml"
  register: copy_es_config

- name: copy elasticsearch service scripts
  template:
    src: "elastic-systemd.j2"
    dest: /etc/systemd/system/elasticsearch.service
    owner: root
    group: root
  become: yes
  register: copy_es_service_script

- name: set vm.max_map_count to 262144 in sysctl
  sysctl: 
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: "vm.max_map_count", value: "262144" }
  become: yes

- name: include es_security.yml
  include: es_security.yml

- name: restart elasticsearch service
  systemd:
    daemon_reload: yes
    state: restarted
    name: elasticsearch.service
    enabled: yes
  become: yes
  register: es_restart
  when: copy_es_service_script.changed or copy_es_config.changed or copy_es.changed

- name: "waiting for elasticsearch to come up"
  uri:
    url: "{{es_api_uri}}"
    method: GET
    user: "{{es_users_elastic}}"
    password: "{{es_passwords_elastic}}"
    force_basic_auth: yes
    status_code: [200, 401]
    validate_certs: no
  register: result
  until: result.status == 200 or result.status == 401
  retries: 60
  delay: 5
  when: es_restart.changed

- name: Making sure elasticsearch is started (in case that there is not any config changes)
  systemd:
    state: started
    name: elasticsearch.service
    enabled: yes
    daemon_reload: no
  become: yes
  register: es_is_started
    
- name: "Waiting for elasticsearch to come up"
  uri:
    url: "{{es_api_uri}}"
    method: GET
    user: "{{es_users_elastic}}"
    password: "{{es_passwords_elastic}}"
    force_basic_auth: yes
    status_code: [200, 401]
    validate_certs: no
  register: result
  until: result.status == 200 or result.status == 401
  retries: 60
  delay: 5
  when: es_is_started.changed

- name: include es_builtin_users.yml
  include: es_builtin_users.yml
