- name: Copy Elasticsearch
  copy:
    src: "files/{{es_repo_file}}"
    dest: "{{apps_dir}}/{{es_repo_file}}"
  register: copyelastic

- name: Create Elasticsearch directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
  with_items:
    - "{{ es_install_dir }}"
    - "{{ es_data_dir }}"
    - "{{ es_logs_dir }}"

- name: Extract Elastic
  unarchive:
    src: "{{ apps_dir }}/{{ es_repo_file }}"
    dest: "{{ es_install_dir }}/"
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: copyelastic.changed

- name: Copy Elastic config
  template:
    src: "elasticsearch.yml.j2"
    dest: "{{ es_install_dir }}/config/elasticsearch.yml"

- name: Copy Elastic start scripts
  template:
    src: "elastic-systemd.j2"
    dest: /etc/systemd/system/elasticsearch.service
    owner: root
    group: root
  become: yes

- name: set vm.max_map_count to 262144 in sysctl
  sysctl: 
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: "vm.max_map_count", value: "262144" }
  become: yes

- name: Start Elastic service
  systemd:
    daemon_reload: yes
    state: restarted
    name: elasticsearch
  become: yes

- name: "Waiting for Elasticsearch to come up"
  uri:
    url: "http://{{ansible_host}}:{{es_port}}/"
    status_code: "200"
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
