---

- name: restart es
  become: yes
  service:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: start es
  become: yes
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: stop es
  become: yes
  service:
    name: elasticsearch
    state: stopped
