logstash_repo_file: "logstash-7.2.0.tar.gz"
logstash_install_dir: "{{bd_app_dir}}/logstash"
logstash_data_dir: "{{bd_data_dir}}/logstash"
logstash_logs_dir: "{{bd_logs_dir}}/logstash"
logstash_patterns_dir: "{{bd_app_dir}}/logstash/patterns"