---

#--------- bootstrap user ----------------
- name: check if kibana keystore already exists
  stat:
    path: "{{ kibana_install_dir }}/data/kibana.keystore"
  register: kibana_keystore

#- debug:
#    msg: "{{ kibana_install_dir }}/data/kibana.keystore"
#
#- debug:
#    msg: "{{kibana_keystore}}"

- name: create the keystore if it doesn't exist yet
  command: >
    {{kibana_install_dir}}/bin/kibana-keystore create
#  args:
#    creates: "{{ kibana_data_dir }}/kibana.keystore"
#  environment:
#    PATH_DATA: "{{ kibana_data_dir }}"
  when: not kibana_keystore.stat.exists

#- name: getting list of available keys in keystore
#  command: >
#    {{kibana_install_dir}}/bin/kibana-keystore list
##  environment:
##    PATH_DATA: "{{ kibana_data_dir }}"
#  register: list_keystore
#  changed_when: False
#  check_mode: no

- name: put kibana password in keystore
  shell: echo "{{kibana_password}}" | {{kibana_install_dir}}/bin/kibana-keystore add -xf 'elasticsearch.password'
#  environment:
#    PATH_DATA: "{{ kibana_data_dir }}"
#  when:
#    - list_keystore is defined and 'bootstrap.password' not in list_keystore.stdout_lines
  no_log: true


- name: adding server.ssl.keyPassphrase to keystore
  shell: echo "{{tls_password}}" | {{kibana_install_dir}}/bin/kibana-keystore add -xf 'server.ssl.keyPassphrase'
  #  environment:
  #    PATH_DATA: "{{ kibana_data_dir }}"
#  when:
#    - list_keystore is defined and 'server.ssl.keyPassphrase' not in list_keystore.stdout_lines
  no_log: true

- name: adding elasticsearch.ssl.keyPassphrase to keystore
  shell: echo "{{tls_password}}" | {{kibana_install_dir}}/bin/kibana-keystore add -xf 'elasticsearch.ssl.keyPassphrase'
  #  environment:
  #    PATH_DATA: "{{ kibana_data_dir }}"
#  when:
#    - list_keystore is defined and 'elasticsearch.ssl.keyPassphrase' not in list_keystore.stdout_lines
  no_log: true