- name: Copy Kibana
  copy:
    src: "files/{{kibana_repo_file}}"
    dest: "{{bd_app_dir}}/{{kibana_repo_file}}"
  register: copykibana

- name: Create Kibana directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ bd_user }}"
  with_items:
    - "{{ kibana_install_dir }}"
    - "{{ kibana_data_dir }}"
    - "{{ kibana_logs_dir }}"

- name: Extract Kibana
  unarchive:
    src: "{{ bd_app_dir }}/{{ kibana_repo_file }}"
    dest: "{{ kibana_install_dir }}/"
    remote_src: yes
    extra_opts:
    - --strip-components=1
  when: copykibana.changed

- name: Copy Kibana config
  template:
    src: "kibana.yml.j2"
    dest: "{{ kibana_install_dir }}/config/kibana.yml"

- name: Copy Kibana start scripts
  template:
    src: "kibana.service.j2"
    dest: /etc/systemd/system/kibana.service
    owner: root
    group: root
  become: yes
  
- name: Start Kibana service
  systemd:
    daemon_reload: yes
    state: restarted
    name: kibana
  become: yes

- name: "Wait for Kibana to come up"
  uri:
    url: "http://{{host_ip}}:{{kibana_port}}/"
    status_code: "200"
  register: result
  until: result.status == 200
  retries: 60
  delay: 5

- name: Import Kibana dashboards
  uri:
    url: http://{{host_ip}}:{{kibana_port}}/api/kibana/dashboards/import?force=true
    method: POST
    headers: 
      kbn-xsrf: true
      Content-Type: "application/json"
    src: files/kibana-dashboards.json
    remote_src: no
    return_content: yes
  run_once: true
  delegate_to: localhost
  register: result
  failed_when: 'result.json.objects[0].error is defined' #fixme: only checks first entry?
