---

- name: restart kibana
  become: yes
  service:
    name: kibana
    state: restarted
    enabled: yes

- name: start kibana
  become: yes
  service:
    name: kibana
    state: started
    enabled: yes

- name: stop kibana
  become: yes
  service:
    name: kibana
    state: stopped
