- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
  become: yes

- name: Create Base Directory
  file:
    path: "{{ base_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ usergroup }}"
  become: yes

- name: Create Apps Directory
  file:
    path: "{{ apps_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ usergroup }}"
  become: yes