#- name: "Update hosts file"
#  lineinfile:
#    dest: /etc/hosts
#    regexp: "{{ hostvars[item]['host_ip'] }}.*{{ item }}$"
#    line: "{{ hostvars[item]['host_ip'] }} {{ item }}"
#    state: present
#  when: hostvars[item]['host_ip'] is defined
#  with_items:
#    - "{{ ansible_play_batch }}"
#  become: yes
#- debug:
#    msg: playhosts {{ ansible_play_batch }}

- name: Create Base Directory
  file:
    path: "{{ base_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ usergroup }}"
  become: yes

- name: Create Apps Directory
  file:
    path: "{{ apps_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ usergroup }}"
  become: yes