- name: CopyJ jdk
  copy:
    src: "files/{{jdk_repo_file}}"
    dest: "{{bd_app_dir}}/{{jdk_repo_file}}"
  register: copyJdk

- name: Create Elastic directories
  file:
    path: "{{ jdk_install_dir }}"
    state: directory
    owner: "{{ bd_user }}"

- name: Extract jdk
  unarchive:
    src: "{{ bd_app_dir }}/{{ jdk_repo_file }}"
    dest: "{{ elastic_install_dir }}/"
    remote_src: yes
    extra_opts:
    - --strip-components=1
  when: copyJdk.changed
