es_repo_file: "elasticsearch-7.6.0-linux-x86_64.tar.gz"
es_install_dir: "{{apps_dir}}/es"
es_conf_dir: "{{es_install_dir}}/config"
es_data_dir: "{{data_dir}}/es"
es_logs_dir: "{{logs_dir}}/es"
es_users_elastic: "elastic"
es_passwords_elastic: "changeme"
es_api_scheme: "https"
es_api_port: 9200
es_api_host: "{{ansible_host}}"
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_security_api: "_security"
kibana_admin_password: changeme
